package main

type ManifestStruct struct {
	Response struct {
		Version                  string `json:"version"`
		MobileAssetContentPath   string `json:"mobileAssetContentPath"`
		MobileGearAssetDataBases []struct {
			Version int    `json:"version"`
			Path    string `json:"path"`
		} `json:"mobileGearAssetDataBases"`
		MobileWorldContentPaths struct {
			En    string `json:"en"`
			Fr    string `json:"fr"`
			Es    string `json:"es"`
			EsMx  string `json:"es-mx"`
			De    string `json:"de"`
			It    string `json:"it"`
			Ja    string `json:"ja"`
			PtBr  string `json:"pt-br"`
			Ru    string `json:"ru"`
			Pl    string `json:"pl"`
			Ko    string `json:"ko"`
			ZhCht string `json:"zh-cht"`
			ZhChs string `json:"zh-chs"`
		} `json:"mobileWorldContentPaths"`
		JSONWorldContentPaths struct {
			En    string `json:"en"`
			Fr    string `json:"fr"`
			Es    string `json:"es"`
			EsMx  string `json:"es-mx"`
			De    string `json:"de"`
			It    string `json:"it"`
			Ja    string `json:"ja"`
			PtBr  string `json:"pt-br"`
			Ru    string `json:"ru"`
			Pl    string `json:"pl"`
			Ko    string `json:"ko"`
			ZhCht string `json:"zh-cht"`
			ZhChs string `json:"zh-chs"`
		} `json:"jsonWorldContentPaths"`
		JSONWorldComponentContentPaths struct {
			En struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"en"`
			Fr struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"fr"`
			Es struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"es"`
			EsMx struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"es-mx"`
			De struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"de"`
			It struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"it"`
			Ja struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"ja"`
			PtBr struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"pt-br"`
			Ru struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"ru"`
			Pl struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"pl"`
			Ko struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"ko"`
			ZhCht struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"zh-cht"`
			ZhChs struct {
				DestinyNodeStepSummaryDefinition                string `json:"DestinyNodeStepSummaryDefinition"`
				DestinyArtDyeChannelDefinition                  string `json:"DestinyArtDyeChannelDefinition"`
				DestinyArtDyeReferenceDefinition                string `json:"DestinyArtDyeReferenceDefinition"`
				DestinyPlaceDefinition                          string `json:"DestinyPlaceDefinition"`
				DestinyActivityDefinition                       string `json:"DestinyActivityDefinition"`
				DestinyActivityTypeDefinition                   string `json:"DestinyActivityTypeDefinition"`
				DestinyClassDefinition                          string `json:"DestinyClassDefinition"`
				DestinyGenderDefinition                         string `json:"DestinyGenderDefinition"`
				DestinyInventoryBucketDefinition                string `json:"DestinyInventoryBucketDefinition"`
				DestinyRaceDefinition                           string `json:"DestinyRaceDefinition"`
				DestinyTalentGridDefinition                     string `json:"DestinyTalentGridDefinition"`
				DestinyUnlockDefinition                         string `json:"DestinyUnlockDefinition"`
				DestinyMaterialRequirementSetDefinition         string `json:"DestinyMaterialRequirementSetDefinition"`
				DestinySandboxPerkDefinition                    string `json:"DestinySandboxPerkDefinition"`
				DestinyStatGroupDefinition                      string `json:"DestinyStatGroupDefinition"`
				DestinyProgressionMappingDefinition             string `json:"DestinyProgressionMappingDefinition"`
				DestinyFactionDefinition                        string `json:"DestinyFactionDefinition"`
				DestinyVendorGroupDefinition                    string `json:"DestinyVendorGroupDefinition"`
				DestinyRewardSourceDefinition                   string `json:"DestinyRewardSourceDefinition"`
				DestinyUnlockValueDefinition                    string `json:"DestinyUnlockValueDefinition"`
				DestinyRewardMappingDefinition                  string `json:"DestinyRewardMappingDefinition"`
				DestinyRewardSheetDefinition                    string `json:"DestinyRewardSheetDefinition"`
				DestinyItemCategoryDefinition                   string `json:"DestinyItemCategoryDefinition"`
				DestinyDamageTypeDefinition                     string `json:"DestinyDamageTypeDefinition"`
				DestinyActivityModeDefinition                   string `json:"DestinyActivityModeDefinition"`
				DestinyMedalTierDefinition                      string `json:"DestinyMedalTierDefinition"`
				DestinyAchievementDefinition                    string `json:"DestinyAchievementDefinition"`
				DestinyActivityGraphDefinition                  string `json:"DestinyActivityGraphDefinition"`
				DestinyActivityInteractableDefinition           string `json:"DestinyActivityInteractableDefinition"`
				DestinyBondDefinition                           string `json:"DestinyBondDefinition"`
				DestinyCharacterCustomizationCategoryDefinition string `json:"DestinyCharacterCustomizationCategoryDefinition"`
				DestinyCharacterCustomizationOptionDefinition   string `json:"DestinyCharacterCustomizationOptionDefinition"`
				DestinyCollectibleDefinition                    string `json:"DestinyCollectibleDefinition"`
				DestinyDestinationDefinition                    string `json:"DestinyDestinationDefinition"`
				DestinyEntitlementOfferDefinition               string `json:"DestinyEntitlementOfferDefinition"`
				DestinyEquipmentSlotDefinition                  string `json:"DestinyEquipmentSlotDefinition"`
				DestinyStatDefinition                           string `json:"DestinyStatDefinition"`
				DestinyInventoryItemDefinition                  string `json:"DestinyInventoryItemDefinition"`
				DestinyInventoryItemLiteDefinition              string `json:"DestinyInventoryItemLiteDefinition"`
				DestinyItemTierTypeDefinition                   string `json:"DestinyItemTierTypeDefinition"`
				DestinyLocationDefinition                       string `json:"DestinyLocationDefinition"`
				DestinyLoreDefinition                           string `json:"DestinyLoreDefinition"`
				DestinyMetricDefinition                         string `json:"DestinyMetricDefinition"`
				DestinyObjectiveDefinition                      string `json:"DestinyObjectiveDefinition"`
				DestinyPlatformBucketMappingDefinition          string `json:"DestinyPlatformBucketMappingDefinition"`
				DestinyPlugSetDefinition                        string `json:"DestinyPlugSetDefinition"`
				DestinyPowerCapDefinition                       string `json:"DestinyPowerCapDefinition"`
				DestinyPresentationNodeDefinition               string `json:"DestinyPresentationNodeDefinition"`
				DestinyProgressionDefinition                    string `json:"DestinyProgressionDefinition"`
				DestinyProgressionLevelRequirementDefinition    string `json:"DestinyProgressionLevelRequirementDefinition"`
				DestinyRecordDefinition                         string `json:"DestinyRecordDefinition"`
				DestinyRewardAdjusterPointerDefinition          string `json:"DestinyRewardAdjusterPointerDefinition"`
				DestinyRewardAdjusterProgressionMapDefinition   string `json:"DestinyRewardAdjusterProgressionMapDefinition"`
				DestinyRewardItemListDefinition                 string `json:"DestinyRewardItemListDefinition"`
				DestinySackRewardItemListDefinition             string `json:"DestinySackRewardItemListDefinition"`
				DestinySandboxPatternDefinition                 string `json:"DestinySandboxPatternDefinition"`
				DestinySeasonDefinition                         string `json:"DestinySeasonDefinition"`
				DestinySeasonPassDefinition                     string `json:"DestinySeasonPassDefinition"`
				DestinySocketCategoryDefinition                 string `json:"DestinySocketCategoryDefinition"`
				DestinySocketTypeDefinition                     string `json:"DestinySocketTypeDefinition"`
				DestinyTraitDefinition                          string `json:"DestinyTraitDefinition"`
				DestinyTraitCategoryDefinition                  string `json:"DestinyTraitCategoryDefinition"`
				DestinyUnlockCountMappingDefinition             string `json:"DestinyUnlockCountMappingDefinition"`
				DestinyUnlockEventDefinition                    string `json:"DestinyUnlockEventDefinition"`
				DestinyUnlockExpressionMappingDefinition        string `json:"DestinyUnlockExpressionMappingDefinition"`
				DestinyVendorDefinition                         string `json:"DestinyVendorDefinition"`
				DestinyMilestoneDefinition                      string `json:"DestinyMilestoneDefinition"`
				DestinyActivityModifierDefinition               string `json:"DestinyActivityModifierDefinition"`
				DestinyReportReasonCategoryDefinition           string `json:"DestinyReportReasonCategoryDefinition"`
				DestinyArtifactDefinition                       string `json:"DestinyArtifactDefinition"`
				DestinyBreakerTypeDefinition                    string `json:"DestinyBreakerTypeDefinition"`
				DestinyChecklistDefinition                      string `json:"DestinyChecklistDefinition"`
				DestinyEnergyTypeDefinition                     string `json:"DestinyEnergyTypeDefinition"`
			} `json:"zh-chs"`
		} `json:"jsonWorldComponentContentPaths"`
		MobileClanBannerDatabasePath string `json:"mobileClanBannerDatabasePath"`
		MobileGearCDN                struct {
			Geometry    string `json:"Geometry"`
			Texture     string `json:"Texture"`
			PlateRegion string `json:"PlateRegion"`
			Gear        string `json:"Gear"`
			Shader      string `json:"Shader"`
		} `json:"mobileGearCDN"`
		IconImagePyramidInfo []interface{} `json:"iconImagePyramidInfo"`
	} `json:"Response"`
	ErrorCode       int    `json:"ErrorCode"`
	ThrottleSeconds int    `json:"ThrottleSeconds"`
	ErrorStatus     string `json:"ErrorStatus"`
	Message         string `json:"Message"`
	MessageData     struct {
	} `json:"MessageData"`
}